In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values

In [2]:
arr1 =  np.random.randint(1, 100, size = (3, 3, 3))
print(arr1)

[[[95 53 88]
  [22 87 45]
  [49 17 84]]

 [[76 20 78]
  [23 77 17]
  [28 52 96]]

 [[77  8 50]
  [53 13 77]
  [20 34 57]]]


# 2. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

In [3]:
val = [1, 2, 3, 4]
mat = np.zeros((5, 5), dtype = int)
for i in range(1, 5):
    mat[i, i-1] = val[i-1]
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
board = np.zeros((8, 8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
mat = np.random.randint(1, 100, size = (5, 5))
mean = mat.mean()
std_dev = mat.std()
normalized_mat = (mat - mean) / std_dev
print("Original random matrix:")
print(mat)
print("\nNormalized matrix:")
print(normalized_mat)

Original random matrix:
[[72  2  4 23 15]
 [10 99 45 65 65]
 [34 29 60 19 17]
 [99 77 30 48 96]
 [69 56 98 35 29]]

Normalized matrix:
[[ 0.79512652 -1.50863409 -1.44281235 -0.81750591 -1.08079283]
 [-1.24534716  1.68371989 -0.09346686  0.56475046  0.56475046]
 [-0.45548638 -0.62004071  0.40019613 -0.94914937 -1.0149711 ]
 [ 1.68371989  0.95968085 -0.58712984  0.00526574  1.58498729]
 [ 0.69639392  0.26855266  1.65080903 -0.42257552 -0.62004071]]


# 5. How to find common values between two arrays?

In [7]:
n = int(input("Enter the size of the arrays: "))
arr1 = []
arr2 = []
arr1 = [int(ele) for ele in (input(f"Enter the {n} elements in to the arr1: ").split())]
arr2 = [int(ele) for ele in (input(f"Enter the {n} elements in to the arr2: ").split())]
array1 = np.array(arr1)
array2 = np.array(arr2)
cmn_vals = np.intersect1d(array1, array2)
print("Common values between array1 and array2:")
print(cmn_vals)

Enter the size of the arrays: 5
Enter the 5 elements in to the arr1: 1 5 4 2 7
Enter the 5 elements in to the arr2: 5 4 8 9 0
Common values between array1 and array2:
[4 5]


# 6. How to get the dates of yesterday, today and tommorow?

In [8]:
from datetime import datetime, timedelta
today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)
print("\nNumPy Datetime Objects:")
print("Yesterday\t: ", yesterday_np)
print("Today\t\t: ", today_np)
print("Tomorrow\t: ", tomorrow_np)


NumPy Datetime Objects:
Yesterday	:  2023-09-20T21:07:57.664504
Today		:  2023-09-21T21:07:57.664504
Tomorrow	:  2023-09-22T21:07:57.664504


# 7. Consider two random arrayA and arrqayB, check if they are equal

In [10]:
n = int(input("Enter the size of the array: "))
arr1 =np.random.randint(1, 20, n)
arr2 = np.random.randint(1, 20, n)
print(f"array1: {arr1}\n")
print(f"array2: {arr2}\n")
flag = np.array_equal(arr1, arr2)
if flag:
    print("Both the arrays are equal")
else:
    print("Both array are not equal")

Enter the size of the array: 3
array1: [ 1  1 16]

array2: [1 8 5]

Both array are not equal


# 8. Crreate random vector of size 10 and replace the maximum value by 0

In [11]:
random_vec = np.random.randint(1,100, 10)
print(f"Random vector\t\t: {random_vec}")
maxi = np.argmax(random_vec)
print(f"maximum element \t: {random_vec[maxi]}")
random_vec[maxi] = 0
print(f"replaced with zero\t: {random_vec}")

Random vector		: [58 76 19 11 74 49 10 22 59 50]
maximum element 	: 76
replaced with zero	: [58  0 19 11 74 49 10 22 59 50]


# 9. How to print all the values of an array?

In [12]:
arr = np.random.randint(1, 100, 15)
for ele in arr:
    print(ele, end=" ")

34 98 24 38 56 49 50 91 63 25 99 40 33 43 19 

# 10. Subtract the mean of each row of matrix

In [13]:
mat = np.random.randint(1, 50, size = (5, 5))
row_means = np.mean(mat, axis=1, keepdims=True)
matrix_means = mat - row_means
print(f"Means:\n {row_means}\n")
print(f"Original Matrix:\n{mat}\n")
print(f"\nMatrix after subtracting row means:\n{matrix_means}\n")
print()

Means:
 [[24.8]
 [14. ]
 [20.8]
 [21.8]
 [26.6]]

Original Matrix:
[[48  7 31  2 36]
 [ 9  9 29  6 17]
 [47  1 31 12 13]
 [ 9 32 31 24 13]
 [24 49 27 21 12]]


Matrix after subtracting row means:
[[ 23.2 -17.8   6.2 -22.8  11.2]
 [ -5.   -5.   15.   -8.    3. ]
 [ 26.2 -19.8  10.2  -8.8  -7.8]
 [-12.8  10.2   9.2   2.2  -8.8]
 [ -2.6  22.4   0.4  -5.6 -14.6]]




# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [15]:
n = int(input("Enter the size of the vector: "))
arr = [int(ele) for ele in(input(f"Enter {n} elements in to the: ").split())]
arr2 = [int(ele) for ele in(input(f"Ente the indices values where +1 want: ").split())]
arr1 = np.array(arr)
arr2 = np.array(arr2)
index = np.unique(arr2)
arr1[arr2] += 1
print(f"After +1 for \n{arr}\n\non indices of\n\n{arr2}\n\nthe result array is \n{arr1}")

Enter the size of the vector: 4
Enter 4 elements in to the: 5 7 4 9
Ente the indices values where +1 want: 1
After +1 for 
[5, 7, 4, 9]

on indices of

[1]

the result array is 
[5 8 4 9]


# 12. How to get the diagonal of a dot product?

In [16]:
mat1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
mat2= np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])
mat_dot = np.dot(mat1, mat2)
diag_values = np.diag(mat_dot)
print(f"\n{mat1}\n\n{mat2}\n\n")
print(f"Dot Product Matrix:\n\n{mat_dot}")
print(f"\nDiagonal Elements of Dot Product:\n\n{diag_values}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Dot Product Matrix:

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

Diagonal Elements of Dot Product:

[ 84 216 366]


# 13. How to find the most frequent value in an array?
x = np.random.randint(0, 10, 50)

In [17]:
x = np.random.randint(0, 10, 50)
cnt = np.bincount(x)
maxi = np.argmax(cnt)
print(f"Array: \n{x}\n\n")
print(f"Most frequent element in the array is:\n{maxi} ")

Array: 
[7 1 9 7 3 4 3 1 3 9 4 1 5 9 5 5 3 2 9 5 0 9 7 9 9 6 7 2 5 6 4 3 7 8 5 1 5
 7 4 1 5 1 1 0 8 6 1 9 1 3]


Most frequent element in the array is:
1 


# 14. how to get the n largest values of an array

In [18]:
n = int(input("Enter the number of largest elements needed: "))
arr = np.random.randint(1, 100, 15)
values = np.partition(arr, -n)[-n:]
print(f"The array is \t\t: {arr}")
print(f"largest {n} elements are\t: {values}")

Enter the number of largest elements needed: 4
The array is 		: [39 76 21  1 45 10 16 20 35 56 75 95 90 63  2]
largest 4 elements are	: [75 76 90 95]


# 15. how to create a record array from a regular array?

In [21]:
regular = [(1, "Hema", 20),
           (2, "Latha", 30),
           (3, "sandhya", 60)]
datatype = [("ID", int), ("Name", 'U10'), ("Age", int)]
structured_array = np.array(regular, dtype=datatype)
print("Structured Array:")
print(structured_array)
print("\nElements by Field Name:")
print("ID\t:", structured_array['ID'])
print("Name\t:", structured_array['Name'])
print("Age\t:", structured_array['Age'])

Structured Array:
[(1, 'Hema', 20) (2, 'Latha', 30) (3, 'sandhya', 60)]

Elements by Field Name:
ID	: [1 2 3]
Name	: ['Hema' 'Latha' 'sandhya']
Age	: [20 30 60]


# 16. How to swap two rows of an array?

In [23]:
arr = np.array([[3, 4, 5, 6],
                [22, 23, 24, 25],
                [31, 32, 33 ,34],
                [41, 42, 43, 44]])
print(f"Before Swapping:\n\n{arr}")
temp = arr[0].copy()
arr[0] = arr[2]
arr[2] = temp
print(f"\nAfter Swapping:\n\n{arr}")

Before Swapping:

[[ 3  4  5  6]
 [22 23 24 25]
 [31 32 33 34]
 [41 42 43 44]]

After Swapping:

[[31 32 33 34]
 [22 23 24 25]
 [ 3  4  5  6]
 [41 42 43 44]]


# 17. Write python code to reshape to the next dimension of numpy array?
x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])

In [24]:
x = np.array([[23, 34, 121], 
              [23, 22, 67], 
              [686, 434, 123]])

print(f"Before Re-shaping:\n\n{x}\n")
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x)

Before Re-shaping:

[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
